// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rMbwfds9KI5dL93r8W3YOyURNseAmA4',
    appId: '1:629428183451:android:09c1166bd3dd3b2dc8413e',
    messagingSenderId: '629428183451',
    projectId: 'brainiax-puzzles-dev',
    storageBucket: 'brainiax-puzzles-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKfpVfAZSK59yOVzy1XR-IJTLAgBzOOBg',
    appId: '1:629428183451:ios:828cc7c24ca84eaec8413e',
    messagingSenderId: '629428183451',
    projectId: 'brainiax-puzzles-dev',
    storageBucket: 'brainiax-puzzles-dev.firebasestorage.app',
    iosBundleId: 'com.brainiax.puzzles.dev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPB8Rf52BEWTnQY0MIae-gc_17tggkq70',
    appId: '1:629428183451:web:b1d0b95f7efeeee4c8413e',
    messagingSenderId: '629428183451',
    projectId: 'brainiax-puzzles-dev',
    authDomain: 'brainiax-puzzles-dev.firebaseapp.com',
    storageBucket: 'brainiax-puzzles-dev.firebasestorage.app',
  );

}